name = "luxx-hotel-api"
main = "app.js"
compatibility_date = "2026-06-17"
compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "./dist" }

# Hyperdrive binding (rename to something unique)
[[hyperdrive]]
binding = "LUXX_DB"
id = "13305a353aae43bdb8f72410e746274c"

# D1 database binding
[[d1_databases]]
binding = "HOTELS_DB"
database_name = "hotels"
database_id = "9332ce4e-46b3-4889-8dbe-907e12277133"

# KV namespace binding (example if you want KV too)
[[kv_namespaces]]
binding = "LUXX_KV"
id = "your-kv-id-here"
