name = "luxx-hotel-api"
main = "src/index.js"
compatibility_date = "2026-06-17"
compatibility_flags = [ "nodejs_compat" ]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "d55104caa85d4d169bab949b0d5afe5a"